import { useNavigate } from 'react-router';
import { VintageLayout } from '../../components/VintageLayout';
import { ArrowLeft } from 'lucide-react';

export function AIPolicyPage() {
  const navigate = useNavigate();

  return (
    <VintageLayout showLogo={false}>
      <div className="max-w-4xl mx-auto px-4 py-8">
        <button
          onClick={() => navigate('/client/home')}
          className="mb-6 text-amber-800 hover:text-amber-900 flex items-center gap-2"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="font-serif text-sm">Return to Dashboard</span>
        </button>

        <div className="bg-amber-50/80 border-4 border-amber-800 p-8 sm:p-12 shadow-lg">
          <h1 className="text-3xl sm:text-4xl text-amber-900 font-serif font-bold mb-2">
            AI Limitations & Data Privacy Policy
          </h1>
          <div className="border-b-2 border-amber-700 mb-8"></div>

          {/* Intro Paragraph */}
          <p className="text-amber-900 font-serif mb-8 leading-relaxed">
            At Safahat, our mission is to empower independent professionals with transparent contract analysis. Because we utilize advanced Artificial Intelligence, we want you to fully understand how your data is handled and the limitations of the technology.
          </p>

          {/* Section 1 */}
          <h2 className="text-xl sm:text-2xl text-amber-900 font-serif font-bold mb-4">
            1. Not Formal Legal Advice
          </h2>
          <p className="text-amber-900 font-serif mb-8 leading-relaxed">
            Safahat AI is an educational and informational tool.{' '}
            <span className="font-bold">
              It does not constitute formal legal counsel, nor does it create an attorney-client relationship.
            </span>{' '}
            While our AI is trained to cross-reference official UAE legal frameworks, it is not a substitute for a licensed legal professional. Always consult a verified lawyer before signing high-risk documents.
          </p>

          {/* Section 2 */}
          <h2 className="text-xl sm:text-2xl text-amber-900 font-serif font-bold mb-4">
            2. Data Privacy & "On-Device" Censorship
          </h2>
          <p className="text-amber-900 font-serif mb-4 leading-relaxed">
            We believe your private information is none of the AI's business. Before any text from your uploaded contract is transmitted to our AI language models, it passes through a rigorous, locally-hosted data scrubbing engine. We automatically redact:
          </p>
          <ul className="list-disc list-inside ml-4 mb-4 text-amber-900 font-serif space-y-2">
            <li>Email addresses</li>
            <li>UAE IBANs and international bank account numbers</li>
            <li>Credit card numbers</li>
            <li>UAE and international phone numbers</li>
          </ul>
          <p className="text-amber-900 font-serif mb-8 leading-relaxed">
            These are replaced with generic tags (e.g., [REDACTED_IBAN]) to ensure maximum privacy.
          </p>

          {/* Section 3 */}
          <h2 className="text-xl sm:text-2xl text-amber-900 font-serif font-bold mb-4">
            3. AI Accuracy and "Hallucinations"
          </h2>
          <p className="text-amber-900 font-serif mb-8 leading-relaxed">
            Artificial Intelligence systems, including the Large Language Models powering Safahat, can occasionally generate incorrect information, miss subtle context, or "hallucinate" non-existent legal clauses. The AI may also fail to distinguish between specific jurisdictional nuances (such as mainland UAE law versus specific free zones like the DIFC or ADGM).
          </p>

          {/* Section 4 */}
          <h2 className="text-xl sm:text-2xl text-amber-900 font-serif font-bold mb-4">
            4. Human Verification Required
          </h2>
          <p className="text-amber-900 font-serif mb-8 leading-relaxed">
            The safety score and risk reports generated by Safahat should be used as a starting point for negotiations, not a final verdict. If a clause is flagged as a{' '}
            <span className="font-bold">DANGER</span>, we strongly encourage you to use our platform to match with a verified human consultant who can review the exact text.
          </p>

          {/* Final Statement */}
          <p className="text-amber-900 font-serif italic text-center mt-12">
            By using Safahat, you acknowledge these limitations and agree to our processing of anonymized contract data.
          </p>
        </div>
      </div>
    </VintageLayout>
  );
}
